#!/usr/bin/env python3
"""PreToolUse hook: stop Claude's file tools changing files that belong to a person, a script or a past measurement.

It only sees Claude's Edit and Write tools, so it stops mistakes: a shell command can still change these files.
Exit code 2 blocks the edit and shows Claude the reason.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(os.environ.get("CLAUDE_PROJECT_DIR") or Path(__file__).resolve().parents[2]).resolve()

LABELS = (
    "Labels are the ground truth for the demo data and the evals. A person changes one by looking at the photo, "
    "never to move a score. Ask the user to make this edit."
)
GENERATED = "It's generated by scripts/build_seed.py: change the script or scripts/demo_places.py, then rebuild."

# (a file, or a folder ending in "/", relative to the repo) and why it's protected
PROTECTED = [
    ("seed/cases/labels.json", LABELS),
    ("evals/labels_real.json", LABELS),
    ("evals/runs/", "A run records what the model said. Make a new run with evals/run.py instead."),
    ("seed/demo_incidents.json", GENERATED),
    ("seed/history.json", GENERATED),
    ("seed/model_cache.json", GENERATED),
    ("seed/photos_web/", GENERATED),
    ("data/", "It's runtime data (the database, uploads and the council password), and the app owns it."),
    ("static/vendor/", "It's third-party code (Leaflet)."),
    ("uv.lock", "Change dependencies with uv add or uv lock, which rewrite it."),
]


def reason(rel: str) -> str | None:
    for target, why in PROTECTED:
        if rel == target or (target.endswith("/") and rel.startswith(target)):
            return why
    if rel.startswith("evals/prompts/") and (ROOT / rel).exists():
        return (
            "A prompt version is fixed once it exists, because its runs hash it. Write the next version as a new file."
        )
    return None


def main() -> int:
    try:
        tool_input = json.load(sys.stdin).get("tool_input") or {}
    except ValueError:
        return 0
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not path:
        return 0
    try:
        rel = Path(path).resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return 0  # outside the repository
    why = reason(rel)
    if why:
        print(f"{rel} is protected. {why}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
